# Generated by Django 3.0.5 on 2020-10-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('path', models.CharField(max_length=255)),
                ('md5', models.CharField(default='', max_length=33)),
                ('size', models.CharField(default=0, max_length=30)),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
            },
        ),
        migrations.CreateModel(
            name='FileInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('path', models.CharField(max_length=255)),
                ('md5', models.CharField(default='', max_length=33)),
                ('size', models.CharField(default=0, max_length=30)),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
            },
        ),
    ]
