# Generated by Django 3.0.5 on 2020-10-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_load', '0003_remove_fileinfo2_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileInfo2',
        ),
    ]
