# Generated by Django 3.0.5 on 2020-11-30 11:44

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_load', '0004_delete_fileinfo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclinationMetaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('zk_num', models.CharField(max_length=255)),
                ('zk_type', models.CharField(max_length=30)),
                ('final_depth', models.CharField(max_length=255)),
                ('final_date', models.DateTimeField()),
                ('depth', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
                ('zk_histogram', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='192.168.55.110:20000钻孔元数据单位/', collection='钻孔元数据GridFS'), upload_to='InclinationMetaModels')),
            ],
            options={
                'verbose_name': '钻孔元数据名',
                'verbose_name_plural': '钻孔元数据名',
                'db_table': '钻孔元数据表',
            },
        ),
    ]
