# Generated by Django 3.0.5 on 2020-11-30 14:42

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_load', '0005_inclinationmetamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclinationmetamodel',
            name='zk_histogram',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='192.168.55.110:20000钻孔元数据位置/', collection='钻孔元数据'), upload_to='InclinationMetaModels'),
        ),
    ]
