# Generated by Django 3.0.5 on 2020-11-30 16:10

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_load', '0006_auto_20201130_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclinationmetamodel',
            name='zk_histogram',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='', collection='钻孔测斜表元数据', database='drill', location=''), upload_to='InclinationMetaModels'),
        ),
        migrations.AlterModelTable(
            name='inclinationmetamodel',
            table='钻孔元数据表测试',
        ),
    ]
