# Generated by Django 3.0.5 on 2020-12-03 11:07

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_load', '0007_auto_20201130_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillMetaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_id', models.CharField(max_length=255)),
                ('zk_num', models.CharField(max_length=255)),
                ('zk_type', models.CharField(max_length=30)),
                ('final_depth', models.CharField(max_length=255)),
                ('final_date', models.DateField()),
                ('upload_date', models.DateField()),
                ('project_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
                ('zk_histogram', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='', collection='钻孔信息元数据', database='drill', location=''), upload_to='InclinationMetaModels')),
            ],
            options={
                'verbose_name': '钻孔元数据名',
                'verbose_name_plural': '钻孔元数据名',
                'db_table': '钻孔信息',
            },
        ),
        migrations.DeleteModel(
            name='InclinationMetaModel',
        ),
    ]
