# Generated by Django 3.0.5 on 2020-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_load', '0008_auto_20201203_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillmetamodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
