# Generated by Django 3.0.5 on 2020-12-10 10:16

from django.db import migrations, models
import djongo.models.fields
import mongeostore_load.models


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_load', '0009_auto_20201203_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('zk_num', models.CharField(max_length=50)),
                ('coordinate_E', models.FloatField(max_length=50)),
                ('coordinate_N', models.FloatField(max_length=50)),
                ('coordinate_R', models.FloatField(max_length=50)),
                ('coordniate', djongo.models.fields.ArrayField(model_container=mongeostore_load.models.DrillCoordniteModel)),
            ],
            options={
                'verbose_name': '钻孔定位表',
                'verbose_name_plural': '钻孔定位表',
            },
        ),
    ]
