# Generated by Django 3.0.5 on 2020-08-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='采集点')),
                ('author', models.CharField(max_length=10, verbose_name='记录人员')),
                ('desc', models.CharField(max_length=100, verbose_name='简介')),
                ('content', models.TextField(verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '测线',
                'verbose_name_plural': '测线',
            },
        ),
    ]
