# Generated by Django 3.0.5 on 2020-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongeostore_app', '0002_mysegy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysegy',
            name='author',
            field=models.CharField(default='henggao', max_length=10, verbose_name='记录人员'),
        ),
        migrations.AlterField(
            model_name='mysegy',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mysegy',
            name='x_line',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mysegy',
            name='y_line',
            field=models.FloatField(default=0),
        ),
    ]
